### ISSUE TITLE
[Feature Request/Question] Support for watchOS or raw code matrix [[Bool]]

### ISSUE THREAD

**Issue by ApolloZhu** [EyreFree/EFQRCode#34]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [x] I have read the [README.md](https://github.com/EyreFree/EFQRCode/blob/master/README.md), but there is no information I need.
- [x] I have searched in [existing issues](https://github.com/EyreFree/EFQRCode/issues?utf8=%E2%9C%93&q=is%3Aissue), 
  - [ ] but did find a same one.

#### Description

I would like to generate QRCode on watchOS. I am aware that `CIFilter` is not available on watchOS, so I ported [qrcodejs](https://github.com/davidshimjs/qrcodejs) to Swift [here](https://github.com/ApolloZhu/swift_qrcodejs), which is able to generate raw code matrix in `[[Bool]]`. I wonder what would possibly be the most easy way to render that using EFQRCode. Thank you very much.

#### Other Comment

Although generating it on the phone and then transfer to the Apple Watch seems to be an acceptable approach. However, as Series 3 became more independent, there are cases where an iPhone is not available when in need.

**Comment by EyreFree** [comment]
Emmmmn, because of the heavy use of CoreImage, it is not possible to use EFQRCode on the watchOS now(There is no CoreImage in watchOS).

If you are going to do some tailoring for EFQRCode, I think at least you need to delete the QRCode recognition function, then replace all types and methods based on CoreImage with CoreGraphics or manual implementation.
